import Head from "next/head";
import Layout from "../../components/Layout";
import RegisterForm from "../../components/RegisterForm";
import authContext from "../../context/auth/authContext";
import { useContext, useEffect } from "react";
export default function Home() {
  const AuthContext = useContext(authContext);

  const { authUser, auth } = AuthContext;

  useEffect(() => {
    authUser();
  }, [auth]);

  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <RegisterForm />
    </>
  );
}
